* highlight-thing.el

  Global minor mode to highlight the thing under point.

  Similar to =highlight-symbol-mode=, but does not rely on font-lock
  functionality and does not provide functionality to navigate to different
  occurrences of the current symbol under point.

  No external dependencies, uses =thingatpt= and =hi-lock= functionality that is
  included with GNU Emacs.

** Installation

   Basic setup:

   #+begin_src emacs-lisp
     (require 'highlight-thing)
     (highlight-thing-mode)
   #+end_src

   The default is to highlight the symbol under point, but you can customize
   =hlt-what-thing= to highlight different components. Set the following to only
   highlight the word under point:

   #+begin_src emacs-lisp
     (setq hlt-what-thing 'word)
   #+end_src

   Customize the face =hi-yellow= to change the colors that are used for
   highlighting.

   You can customize the delay before this mode attempts to highlight the thing
   under point. For example, push it out to 1.5 seconds from the default 0.5:

   #+begin_src emacs-lisp
     (setq hlt-delay-seconds 1.5)
   #+end_src
